version: '3.7'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"
        container_name: postgres
        volumes:
            - ./postgres_home:/root/postgres_home

    webserver:
        image: shepll/docker-airflow:latest
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - AIRFLOW__CORE__FERNET_KEY=9dVU473cQDDn7iD18I3EvDSgio3lAc_Q66ZXrEAbpG4=
            - AIRFLOW__CORE__EXECUTOR=LocalExecutor
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - /home/airflow/airflow_home:/usr/local/airflow/dags
            - /home/airflow/airflow_plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
        container_name: airflow